// crackdown - ReXGlue Recompiled Project
// Generated by: rexglue migrate
//
// This file is SDK-managed. Customizations go in virtual hook overrides.
// Running 'rexglue migrate' will overwrite this file.

#include "generated/crackdown_config.h"
#include "generated/crackdown_init.h"

#include <rex/rex_app.h>
#include <rex/filesystem/devices/host_path_device.h>
#include <rex/graphics/flags.h>

#include "cache.h"
#include "controller_input.h"
#ifdef _WIN32
#include "automation.h"
#include "timer_resolution.h"
#include <rex/graphics/graphics_system.h>
#endif

REXCVAR_DEFINE_BOOL(fix_lighting, false, "Game Enhancements", "Fix lighting calculation, currently halves FPS but improves visibility and color/brightness accuracy.");
REXCVAR_DEFINE_BOOL(fix_light_occlusion, true, "Game Enhancements", "Fix light source coronas being visible through walls.");
REXCVAR_DEFINE_BOOL(misc_performance_improvements, false, "Game Enhancements", "Disables bloom and shadows to potentially improve performance.");
REXCVAR_DEFINE_BOOL(show_perfgraph, false, "Game Enhancements", "Show FPS counter in the top right and performance graph in the left half of the screen.");
#ifdef _WIN32
REXCVAR_DEFINE_BOOL(automation, false, "Debug", "Enable local automated controller input and guest frame capture for testing.");
REXCVAR_DEFINE_BOOL(high_resolution_timer, true, "Performance", "Request 1 ms Windows timer precision for runtime waits (restart required).")
    .lifecycle(rex::cvar::Lifecycle::kRequiresRestart);
#endif

class CrackdownApp : public rex::ReXApp {
public:
    using rex::ReXApp::ReXApp;

    static std::unique_ptr<rex::ui::WindowedApp> Create(
        rex::ui::WindowedAppContext& ctx) {
    return std::unique_ptr<CrackdownApp>(new CrackdownApp(ctx, "crackdown",
        {PPC_CODE_BASE, PPC_CODE_SIZE, PPC_IMAGE_BASE,
            PPC_IMAGE_SIZE, PPCFuncMappings}));
    }
  
    void OnPreSetup(rex::RuntimeConfig& config) override
    {
        config.input_factory = CreateControllerInputSystem;
#ifdef _WIN32
        if (REXCVAR_GET(high_resolution_timer)) {
            timer_resolution_ = std::make_unique<WindowsTimerResolution>();
            if (timer_resolution_->active()) {
                REXLOG_INFO("Windows 1 ms timer precision enabled");
            } else {
                REXLOG_WARN("Windows 1 ms timer request failed; runtime waits may be slower");
            }
        }
        if (REXCVAR_GET(automation)) {
            automation_ = std::make_unique<AutomationSession>();
            config.input_factory = [this](bool) { return automation_->CreateInputSystem(); };
        }
#endif
    }

    void OnPostSetup() override
    {
        if (REXCVAR_GET(fix_lighting))
        {
            // Fix lighting (https://github.com/xenia-canary/game-compatibility/issues/102#issuecomment-2385029628)
            REXCVAR_SET(d3d12_readback_resolve, true);
        }

        // Fix invalid fetch constant type error
        REXCVAR_SET(gpu_allow_invalid_fetch_constants, true);

        // Fix infinite loading screen (https://github.com/xenia-canary/game-compatibility/issues/102#issuecomment-1222126375)
        auto file_system = runtime()->file_system();

        auto cache_device = std::make_unique<CacheDevice>("\\CACHE");
        if (!cache_device->Initialize()) {
            REXLOG_ERROR("Unable to initialize cache device.");
        }
        else {
            if (!file_system->RegisterDevice(std::move(cache_device))) {
                REXLOG_ERROR("Unable to register cache device.");
            }
            else {
                file_system->RegisterSymbolicLink("cache:", "\\CACHE");
            }
        }

        // Below memory writes are originally made by Adrian (https://github.com/xenia-canary/game-patches/blob/main/patches/4D5307DC%20-%20Crackdown%20%28TU0%29.patch.toml)
        auto membase = rex::system::kernel_state()->memory()->virtual_membase();

        if (REXCVAR_GET(fix_light_occlusion))
        {
            // Fix seeing lights through walls by disabling them.
            *reinterpret_cast<bool*>(membase + 0x82BAA3AD) = false; // "togglegloballights" command.
        }

        if (REXCVAR_GET(show_perfgraph))
        {
            *reinterpret_cast<bool*>(membase + 0x82DE4F14) = true; // "fps" command.
            *reinterpret_cast<bool*>(membase + 0x82DE4D1A) = true; // "perfgraph" command.
            *reinterpret_cast<bool*>(membase + 0x82DE25A9) = true; // Sets fps/perfgraph to have red text.
        }

        if (REXCVAR_GET(misc_performance_improvements))
        {
            // Performance-improving commands
            *reinterpret_cast<bool*>(membase + 0x82BAA3AA) = true; // "togglebloom" command.
            *reinterpret_cast<bool*>(membase + 0x82DE25B3) = false; // Disable shadows.
        }
    }

    void OnCreateDialogs(rex::ui::ImGuiDrawer* drawer) override
    {
#ifdef _WIN32
        if (automation_) {
            auto* graphics = static_cast<rex::graphics::GraphicsSystem*>(runtime()->graphics_system());
            automation_->StartCapture(graphics->presenter(), user_data_root().parent_path() / "automation" / std::to_string(GetCurrentProcessId()));
        }
#endif
        // ReXApp owns the settings, console and debug dialogs. Creating them
        // again also replaces the SDK's key bindings and repeats every draw.
        (void)drawer;
    }

    void OnShutdown() override
    {
#ifdef _WIN32
        if (automation_) automation_->StopCapture();
#endif
    }

#ifdef _WIN32
    std::unique_ptr<WindowsTimerResolution> timer_resolution_;
    std::unique_ptr<AutomationSession> automation_;
#endif
};

REX_DEFINE_APP(crackdown, CrackdownApp::Create)

// Xam Stubs
PPC_STUB(__imp__XamUserCreateStatsEnumerator);
PPC_STUB(__imp__XamShowFriendsUI);
PPC_STUB(__imp__XamShowGamerCardUIForXUID);
PPC_STUB(__imp__XamShowMarketplaceUI);
PPC_STUB(__imp__XamUserGetMembershipTierFromXUID);
PPC_STUB(__imp__XamUserGetOnlineCountryFromXUID);
PPC_STUB(__imp__XamContentLaunchImage);
PPC_STUB(__imp__XamVoiceSubmitPacket);

// Kernel Stubs
PPC_STUB(__imp__KeSaveFloatingPointState);
PPC_STUB(__imp__KeRestoreFloatingPointState);

// NetDll Stubs
PPC_STUB(__imp__NetDll_XNetCreateKey);
PPC_STUB(__imp__NetDll_XNetRegisterKey);
PPC_STUB(__imp__NetDll_XNetUnregisterKey);
PPC_STUB(__imp__NetDll_XNetServerToInAddr);
PPC_STUB(__imp__NetDll_XNetConnect);
PPC_STUB(__imp__NetDll_XNetGetConnectStatus);
PPC_STUB(__imp__NetDll_XNetQosLookup);
PPC_STUB(__imp__NetDll_getsockopt);
PPC_STUB(__imp__NetDll_getsockname);
PPC_STUB(__imp__NetDll_getpeername);
PPC_STUB(__imp__NetDll_WSAEventSelect);

// XNetLogon Stubs
PPC_STUB(__imp__XNetLogonGetTitleID);

// XeCrypt Stubs
PPC_STUB(__imp__XeCryptBnQwBeSigVerify);
PPC_STUB(__imp__XeCryptRotSumSha);

// XeKeys Stubs
PPC_STUB(__imp__XeKeysGetKey);
